### ISSUE TITLE
I have some question about using biomedicus

### ISSUE THREAD

**Issue by bindl159** [nlpie/biomedicus#82]
I am doing research based on Biomedicus.
I would like to know how to Train the Word Model and Suffix Model stored in RocksDB.
And I want to receive Train Data of both models.
I saw the code related to Train.
But I do not understand it, so I'd like you to know how to use it.

I'll wait for your kind reply.
Thanks for reading.

**Comment by benknoll-umn** [comment]
Hello,
What version are using / do you want to use?

I'll work on a documentation page for part of speech training and how the data is stored in RocksDB.

**Comment by benknoll-umn** [comment]
I added some documentation related to training TnT part-of-speech models. You can find it [here](https://github.com/nlpie/biomedicus/wiki/Training-TnT-Part-of-speech-tagger). You may need to read some [UIMA documentation](https://uima.apache.org/documentation.html#manuals_and_guides) for a introduction on how to run UIMA pipelines.

**Comment by bindl159** [comment]
Thanks for reply.
I understood everything you said.
I also tried Training tests with test data.[http://www.nltk.org/nltk_data/](url) is TestData

I do not know what data you used to train. (Meaning that data in PTB format can not be found)
I want you to give me the data you used.

I'll be waiting for a kind reply.

**Comment by benknoll-umn** [comment]
We used the Penn Treebank III - https://www.ldc.upenn.edu/language-resources/data/obtaining and the MiPaCQ Treebank - https://www.ncbi.nlm.nih.gov/pubmed/23355458. Unfortunately I can't provide either of the corpora, Penn Treebank is licensed and MiPaCQ is not public.

**Comment by bindl159** [comment]
Hello,
I have a question.
Why did you train TNT Model in Penn TreeBank format?
I have had this question because you support parsing separately with Stanford Parser and SyntaxNet.

**Comment by benknoll-umn** [comment]
For performance reasons the parser is not enabled by default. Currently, we plan on only using it on a small percentage of sentences for social history / family history detection.

**Comment by bindl159** [comment]
So why use the Penn treebank structure for tnt training?

**Comment by benknoll-umn** [comment]
PTB contains part-of-speech tags, and those are just the corpora we had available.

**Comment by GaryYufei** [comment]
Hi @benknoll-umn, is there a way to get MiPaCQ corpus. I would like to conduct research in domain adaptation. This corpus can play an important role as test bed. Thanks.
