### ISSUE TITLE
UML-Licensed Version of Data Files for Biomedicus 3.0b8?

### ISSUE THREAD

**Issue by DaveJohnson8080** [nlpie/biomedicus#85]
The latest 3.0b8 version of Biomedicus requires the newer 3.0b8-versioned data.

The downloads page has the "standard" data for download. (e.g. biomedicus-3.0b8-standard-data.zip)

Is there a 3.0b8 UML-licensed version as in previous versions? (e.g. biomedicus-3.0b8-umls-license-required-data.zip)

https://nlpie.github.io/downloads/

Thanks!

**Comment by benknoll-umn** [comment]
The downloads should contain the latest version now.
