### ISSUE TITLE
Sentence Parsing Differences Between 3.0b7 and 3.0b8

### ISSUE THREAD

**Issue by DaveJohnson8080** [nlpie/biomedicus#86]
**Describe the bug**
(See attachment for inputs/outputs)
Sentence parsing on simple document with headers seems to be slightly off between 3.0b7 and 3.0b8. The issues in 3.0b8 seems to be affecting the ability to identify headers/sections. The failure seems to happen at the early part of the document, but then has a lasting effect on section parsing.

**To Reproduce**
Run the full pipeline for the sample Source Doc in both 3.0b7 and 3.0b8, then compare results.

**Expected behavior**
Sentence and section parsing should be consistent between 3.0b7 and 3.0b8.

**Terminal Output**
None

**Environment**
 - OS: Ubuntu 18.04
 - Version 3.0b8
 - Python Version 3.69
 - Java Version OpenJDK 11.0.10+9

**Additional context**
The test scenario and results are in the attached sheet.
[20210218-SentencesIssue.xlsx](https://github.com/nlpie/biomedicus3/files/6006590/20210218-SentencesIssue.xlsx)

**Comment by benknoll-umn** [comment]
I made a bad assumption about pytorch serialization and the beta 8 model is missing a significant component. I'm starting the process of rolling back and will release a new version today. 

We have an evaluation test set for sentences, but it's not fully automated and the data is PHI / not part of the developer environment. I wrongly thought that the changes made in beta 8 didn't warrant re-evaluation. I'll add some non-PHI smoke tests for sentences moving forward.

**Comment by DaveJohnson8080** [comment]
Thanks, Ben!
